---
- name: Install ruby and bundler
  hosts: all
  become: true
  tasks:
  - name: Apt update and install ruby-full ruby-bundler build-essential
    apt:
      pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
      update_cache: yes
